In [1]:

import matplotlib.pyplot as plt
import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


In [63]:
df = pd.read_csv('/content/dataset - dataset.csv')

df


Year  Infilation      gold       bse  salary
0   1961    0.021454  0.065555 -0.038047  0.1000
1   1962    0.044056  0.087006 -0.173226  0.0909
2   1963    0.083536  0.244007  0.136790  0.0417
3   1964    0.085517  0.181688 -0.043198  0.0400
4   1965    0.083004  0.106246 -0.213598  0.0769
..   ...         ...       ...       ...     ...
57  2018    0.038842  0.125077  0.059100  0.0323
58  2019    0.024055 -0.027455  0.143800  0.0313
59  2020    0.047465  0.054303  0.157400  0.0303
60  2021    0.085385 -0.065716  0.219400  0.0294
61  2022    0.082259 -0.019660  0.044500  0.0286

[62 rows x 5 columns]

In [64]:
x = df.iloc[:61, 0].values.reshape(-1, 1)  # Reshape x to make it 2D
y = df.iloc[:61, 1].values.reshape(-1, 1)  # Reshape y to make it 2D

In [65]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 110)

In [8]:
import pycaret

In [70]:
# Training the linear regression model

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

model = LinearRegression()
model.fit(X_train, y_train)

# Making predictions on the test set

y_pred = model.predict(X_test)

# # # Evaluating the model
# # results = {}
# # results['Logistic Regression'] = [accuracy_score(y_test, y_pred),
# #                                   precision_score(y_test, y_pred, average='weighted'),
# #                                   recall_score(y_test, y_pred, average='weighted'),
# #                                   f1_score(y_test, y_pred, average='weighted')
# #     ]
# # df_results = pd.DataFrame.from_dict(results, orient='index', columns=['Accuracy', 'Precision', 'Recall', 'F1-Score', 'Training Time'])

# # df_results
# from sklearn.metrics import mean_squared_error

# Calculate mean squared error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 0.0023837304082487813


In [67]:
y_pred

array([[0.07077756],
       [0.06736854],
       [0.06688153],
       [0.07019316],
       [0.06834254],
       [0.06843995],
       [0.06824514],
       [0.07136197],
       [0.07145937],
       [0.07155677],
       [0.06990096],
       [0.06960875],
       [0.06882955]])

In [71]:
model.predict([[2024]])*100

array([[6.63945278]])

In [73]:
with open('/content/inflation_precit.pkl', 'wb') as pickle_file:
    pickle.dump(model, pickle_file)

In [74]:
x_sal = df.iloc[:61, 0].values.reshape(-1, 1)  # Reshape x to make it 2D
y_sal = df.iloc[:61, 4].values.reshape(-1, 1)  # Reshape y to make it 2D

In [79]:
X_sal_train, X_sal_test, y_sal_train, y_sal_test = train_test_split(x_sal, y_sal, test_size = 0.2, random_state = 110)

In [80]:
model_sal = LinearRegression()
model_sal.fit(X_sal_train, y_sal_train)

# Making predictions on the test set

y_sal_pred = model_sal.predict(X_sal_test)
mse_sal = mean_squared_error(y_sal_test, y_sal_pred)
print("Mean Squared Error (MSE):", mse_sal)

Mean Squared Error (MSE): 0.00010414543938205977


In [81]:
with open('/content/sallary.pkl', 'wb') as pickle_file:
    pickle.dump(model_sal, pickle_file)

In [83]:
x_gold = df.iloc[:61, 0].values.reshape(-1, 1)  # Reshape x to make it 2D
y_gold = df.iloc[:61, 2].values.reshape(-1, 1)  # Reshape y to make it 2D
X_gold_train, X_gold_test, y_gold_train, y_gold_test = train_test_split(x_gold, y_gold, test_size = 0.2, random_state = 110)
model_gold = LinearRegression()
model_gold.fit(X_gold_train, y_gold_train)

# Making predictions on the test set

y_gold_pred = model_gold.predict(X_gold_test)
mse_gold = mean_squared_error(y_gold_test,y_gold_pred)
print("Mean Squared Error (MSE):", mse_gold)

Mean Squared Error (MSE): 0.0062289885974622355


In [84]:
with open('/content/gold.pkl', 'wb') as pickle_file:
    pickle.dump(model_gold, pickle_file)

In [85]:
model_gold.predict([[2024]])*100

array([[4.15021339]])

In [88]:
x_bse = df.iloc[:61, 0].values.reshape(-1, 1)  # Reshape x to make it 2D
y_bse = df.iloc[:61, 3].values.reshape(-1, 1)  # Reshape y to make it 2D
X_bse_train, X_bse_test, y_bse_train, y_bse_test = train_test_split(x_bse, y_bse, test_size = 0.2, random_state = 110)
model_bse = LinearRegression()
model_bse.fit(X_bse_train, y_bse_train)

# Making predictions on the test set

y_bse_pred = model_bse.predict(X_bse_test)
mse_bse = mean_squared_error(y_bse_test,y_bse_pred)
print("Mean Squared Error (MSE):", mse_bse)

Mean Squared Error (MSE): 0.18027016132761367


In [89]:
model_bse.predict([[2024]])*100

array([[15.76746832]])

In [90]:
with open('/content/bse.pkl', 'wb') as pickle_file:
    pickle.dump(model_bse, pickle_file)